GET http://localhost:3000

###

GET http://localhost:3000/register

###

POST http://localhost:3000/register
Content-Type: "application/json"

{
    "name": "Erik",
    "email": "test@email.com",
    "password": "Password123"
}

###

GET http://localhost:3000/login